# Student Performance & Churn Analysis - Data Preprocessing

This notebook focuses on cleaning and transforming the raw university student database into a standardized format suitable for Exploratory Data Analysis (EDA) and Predictive Modeling.

## 1.0 Imports and Configuration

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set default visualization style
sns.set_theme(style="whitegrid")

## 2.0 Load and Cleaning

In [2]:
# 1. Beolvasás (kezeljük a magyar tizedesvesszőt és szeparátort)
df_raw = pd.read_csv('../data/AA_mintafeladat.csv', sep=';', decimal=',', encoding='latin1')
df_raw.head()

,Key,Képzés jogviszony kezdete,Modulkód,KépzésStátusz,Tagozat,Képzési szint,Félév,Pénzügyi státusz,FélévesStátusz,Nem,Születési dátum,Irányítószám,FélévSorszám,Aktív félévek,Féléven felvett kredit,Féléven kumulált felvett kredit,Féléven teljesített kredit,Féléven kumulált teljesített kredit,Átlag,Kumulált átlag
0,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2010.11.01,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,1,7.0,33.0,33.0,33.0,33.0,3.64,3.64
1,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2010.11.02,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,2,7.0,31.0,64.0,31.0,64.0,4.71,4.16
2,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2011.12.01,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,3,7.0,30.0,94.0,30.0,94.0,4.27,4.19
3,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2011.12.02,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,4,7.0,31.0,125.0,31.0,125.0,4.06,4.16
4,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2012/13/1,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,5,7.0,31.0,156.0,31.0,156.0,4.16,4.16

## 3.0 Column Standardization

In [3]:
COLUMN_TRANSLATION = {
    'Key': 'student_id',
    'Képzés jogviszony kezdete': 'enrollment_date',
    'Modulkód': 'major_code',
    'KépzésStátusz': 'status_at_record',
    'Tagozat': 'study_mode',
    'Képzési szint': 'degree_level',
    'Félév': 'semester_id',
    'Pénzügyi státusz': 'funding_type',
    'FélévesStátusz': 'semester_active_status',
    'Nem': 'gender',
    'Születési dátum': 'birth_date',
    'Irányítószám': 'zip_code',
    'FélévSorszám': 'term_number',
    'Aktív félévek': 'total_active_terms',
    'Féléven felvett kredit': 'credits_taken_term',
    'Féléven kumulált felvett kredit': 'credits_taken_cum',
    'Féléven teljesített kredit': 'credits_done_term',
    'Féléven kumulált teljesített kredit': 'credits_done_cum',
    'Átlag': 'gpa_term',
    'Kumulált átlag': 'gpa_cum'
}

df = df_raw.rename(columns=COLUMN_TRANSLATION)
df.head()

,student_id,enrollment_date,major_code,status_at_record,study_mode,degree_level,semester_id,funding_type,semester_active_status,gender,birth_date,zip_code,term_number,total_active_terms,credits_taken_term,credits_taken_cum,credits_done_term,credits_done_cum,gpa_term,gpa_cum
0,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2010.11.01,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,1,7.0,33.0,33.0,33.0,33.0,3.64,3.64
1,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2010.11.02,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,2,7.0,31.0,64.0,31.0,64.0,4.71,4.16
2,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2011.12.01,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,3,7.0,30.0,94.0,30.0,94.0,4.27,4.19
3,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2011.12.02,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,4,7.0,31.0,125.0,31.0,125.0,4.06,4.16
4,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2012/13/1,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,5,7.0,31.0,156.0,31.0,156.0,4.16,4.16

### 3.1 Categorical Data Audit

In [4]:
# List of categorical columns to investigate
categorical_columns = [
    'status_at_record', 
    'study_mode', 
    'degree_level', 
    'funding_type', 
    'semester_active_status', 
    'gender'
]

print("--- UNIQUE VALUES PER CATEGORICAL COLUMN ---\n")

for col in categorical_columns:
    if col in df.columns:
        unique_values = df[col].dropna().unique().tolist()
        print(f"Column: {col}")
        print(f"Number of unique values: {len(unique_values)}")
        print(f"Values: {unique_values}")
        print("-" * 40)
    else:
        print(f"Error: Column '{col}' not found in the DataFrame!")

--- UNIQUE VALUES PER CATEGORICAL COLUMN ---

Column: status_at_record
Number of unique values: 21
Values: ['Aktív', 'Diplomát szerzett', 'Törölt', 'Passzív', 'Részismeretes(végzett)', 'Záróvizsgát tett', 'Abszolvált', 'Szakváltoztató', 'Sikeres záróvizsga', 'Bejelentés nélkül távozott', 'Aktív vendéghallgató', 'Sikertelen záróvizsga', 'Elhunyt', 'Képzés váltó', 'Még nem meghatározott', 'Saját kérésre törölve', 'Tagozat váltó', 'Felvett', 'Nem beszámító aktív', 'Intézményváltoztató', 'Átsorolva más jelû tantervbe']
----------------------------------------
Column: study_mode
Number of unique values: 2
Values: ['Nappali', 'Levelezõ']
----------------------------------------
Column: degree_level
Number of unique values: 2
Values: ['alapképzés (BA/BSc)', 'mesterképzés (MA/MSc)']
----------------------------------------
Column: funding_type
Number of unique values: 26
Values: ['Államilag finanszírozott', 'Költségtérítéses', 'Államilag támogatott', 'Államilag támogatott (képzési idõn túli)', 'Önköltséges', 'Állami részösztöndíjas', 'Állami ösztöndíjas', 'Költségtérítéses (másoddiplomás)', 'Államilag finanszírozott (képzési idõn túli)', 'Miniszteri ösztöndíjas', 'Költségtérítés mentes (GYES...)', 'Költségtérítéses (képzési idõn túli)', 'A1 kategóriás külföldi ösztöndíjas', 'Részképzés', 'Államilag finanszírozott túllépõ', 'Még nem meghatározott', 'Költségtérítés mentes', 'Normatív támogatással A3 HTM', 'Költségtérítéses (vendéghallgató)', 'B külf. külsõ tám. ösztöndíj', 'Egyéb', 'Államilag támogatott (vendéghallgató)', 'Költségtérítéses (párhuzamos)', 'C kategóriás külföldi ösztöndíjas', 'Önköltséges külföldi', 'A3R Részképzõs HTM normatív támogatással']
----------------------------------------
Column: semester_active_status
Number of unique values: 21
Values: ['Aktív', 'Passzív', 'Aktív vendéghallgató', 'Évhalasztó', 'Akkreditált', 'Felvett', 'Még nem meghatározott', 'Törölt', 'Áthallgató', 'Abszolvált', 'Záróvizsgára vár', 'Szakváltoztató', 'Nem beszámító aktív', 'Részismeretes(végzett)', 'Képzés váltó', 'Elhunyt', 'Bejelentés nélkül távozott', 'Szünetel', 'Átsorolva más jelû tantervbe', 'Passzív vendéghallgató', 'Saját kérésre törölve']
----------------------------------------
Column: gender
Number of unique values: 2
Values: ['Nõ', 'Férfi']
----------------------------------------

## 4.0 Categorical Translation and Mapping

In [5]:
status_at_record_map = {
    "Aktív": "Active",
    "Diplomát szerzett": "Graduated",
    "Törölt": "Deleted",
    "Passzív": "Inactive",
    "Részismeretes(végzett)": "Partial studies completed",
    "Záróvizsgát tett": "Final exam taken",
    "Abszolvált": "Completed coursework (absolved)",
    "Szakváltoztató": "Changed major",
    "Sikeres záróvizsga": "Successful final exam",
    "Bejelentés nélkül távozott": "Left without notice",
    "Aktív vendéghallgató": "Active guest student",
    "Sikertelen záróvizsga": "Failed final exam",
    "Elhunyt": "Deceased",
    "Képzés váltó": "Changed program",
    "Még nem meghatározott": "Not yet defined",
    "Saját kérésre törölve": "Deleted upon own request",
    "Tagozat váltó": "Changed study track",
    "Felvett": "Admitted",
    "Nem beszámító aktív": "Active (non-credit)",
    "Intézményváltoztató": "Changed institution",
    "Átsorolva más jelû tantervbe": "Reclassified to different curriculum"
}

study_mode_map = {
    "Nappali": "Full-time",
    "Levelezõ": "Part-time"
}

degree_level_map = {
    "alapképzés (BA/BSc)": "Bachelor's degree (BA/BSc)",
    "mesterképzés (MA/MSc)": "Master's degree (MA/MSc)"
}

funding_type_map = {
    "Államilag finanszírozott": "State-funded",
    "Költségtérítéses": "Tuition-fee paying",
    "Államilag támogatott": "State-supported",
    "Államilag támogatott (képzési idõn túli)": "State-supported (beyond study period)",
    "Önköltséges": "Self-funded",
    "Állami részösztöndíjas": "Partial state scholarship",
    "Állami ösztöndíjas": "State scholarship",
    "Költségtérítéses (másoddiplomás)": "Tuition-fee paying (second degree)",
    "Államilag finanszírozott (képzési idõn túli)": "State-funded (beyond study period)",
    "Miniszteri ösztöndíjas": "Ministerial scholarship",
    "Költségtérítés mentes (GYES...)": "Tuition-free (childcare leave etc.)",
    "Költségtérítéses (képzési idõn túli)": "Tuition-fee paying (beyond study period)",
    "A1 kategóriás külföldi ösztöndíjas": "A1 category foreign scholarship",
    "Részképzés": "Partial studies",
    "Államilag finanszírozott túllépõ": "State-funded (exceeding study period)",
    "Még nem meghatározott": "Not yet defined",
    "Költségtérítés mentes": "Tuition-free",
    "Normatív támogatással A3 HTM": "A3 HTM with normative support",
    "Költségtérítéses (vendéghallgató)": "Tuition-fee paying (guest student)",
    "B külf. külsõ tám. ösztöndíj": "B foreign external support scholarship",
    "Egyéb": "Other",
    "Államilag támogatott (vendéghallgató)": "State-supported (guest student)",
    "Költségtérítéses (párhuzamos)": "Tuition-fee paying (parallel program)",
    "C kategóriás külföldi ösztöndíjas": "C category foreign scholarship",
    "Önköltséges külföldi": "Self-funded foreign student",
    "A3R Részképzõs HTM normatív támogatással": "A3R partial training HTM with normative support"
}

semester_active_status_map = {
    "Aktív": "Active",
    "Passzív": "Inactive",
    "Aktív vendéghallgató": "Active guest student",
    "Évhalasztó": "Deferred year",
    "Akkreditált": "Accredited",
    "Felvett": "Admitted",
    "Még nem meghatározott": "Not yet defined",
    "Törölt": "Deleted",
    "Áthallgató": "Cross-registered student",
    "Abszolvált": "Completed coursework (absolved)",
    "Záróvizsgára vár": "Awaiting final exam",
    "Szakváltoztató": "Changed major",
    "Nem beszámító aktív": "Active (non-credit)",
    "Részismeretes(végzett)": "Partial studies completed",
    "Képzés váltó": "Changed program",
    "Elhunyt": "Deceased",
    "Bejelentés nélkül távozott": "Left without notice",
    "Szünetel": "On leave",
    "Átsorolva más jelû tantervbe": "Reclassified to different curriculum",
    "Passzív vendéghallgató": "Inactive guest student",
    "Saját kérésre törölve": "Deleted upon own request"
}

gender_map = {
    "Nõ": "Female",
    "Férfi": "Male"
}

# Apply replacements
df["status_at_record"] = df["status_at_record"].replace(status_at_record_map)
df["study_mode"] = df["study_mode"].replace(study_mode_map)
df["degree_level"] = df["degree_level"].replace(degree_level_map)
df["funding_type"] = df["funding_type"].replace(funding_type_map)
df["semester_active_status"] = df["semester_active_status"].replace(semester_active_status_map)
df["gender"] = df["gender"].replace(gender_map)

# Final check for missing values in processed columns
print(df[categorical_columns].isna().sum())

status_at_record          0
study_mode                0
degree_level              0
funding_type              0
semester_active_status    0
gender                    0
dtype: int64

## 5.0 Temporal Feature Engineering

In [6]:
# Extract the last two digits of birth_date and convert to full year
temp_year = df['birth_date'].str.slice(-2).astype(int)
df['birth_date'] = temp_year.apply(lambda x: 1900 + x if x > 25 else 2000 + x)
df.rename(columns={'birth_date': 'birth_year'}, inplace=True)

df.head()

,student_id,enrollment_date,major_code,status_at_record,study_mode,degree_level,semester_id,funding_type,semester_active_status,gender,birth_year,zip_code,term_number,total_active_terms,credits_taken_term,credits_taken_cum,credits_done_term,credits_done_cum,gpa_term,gpa_cum
0,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2010.11.01,State-funded,Active,Female,1991,1126,1,7.0,33.0,33.0,33.0,33.0,3.64,3.64
1,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2010.11.02,State-funded,Active,Female,1991,1126,2,7.0,31.0,64.0,31.0,64.0,4.71,4.16
2,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2011.12.01,State-funded,Active,Female,1991,1126,3,7.0,30.0,94.0,30.0,94.0,4.27,4.19
3,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2011.12.02,State-funded,Active,Female,1991,1126,4,7.0,31.0,125.0,31.0,125.0,4.06,4.16
4,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2012/13/1,State-funded,Active,Female,1991,1126,5,7.0,31.0,156.0,31.0,156.0,4.16,4.16

## 6.0 Save Processed Data

In [7]:
df.to_csv('../data/student_data_cleaned.csv', index=False, encoding='utf-8')
print("Preprocessing finished. Cleaned data saved to: ../data/student_data_cleaned.csv")

Preprocessing finished. Cleaned data saved to: ../data/student_data_cleaned.csv