# Student Performance & Churn Analysis - Data Preprocessing

This notebook focuses on cleaning and transforming the raw university student database into a standardized format suitable for Exploratory Data Analysis (EDA) and Predictive Modeling.

## 1.0 Imports and Configuration

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set default visualization style
sns.set_theme(style="whitegrid")

## 2.0 Load and Cleaning

In [2]:
# 1. Beolvasás (kezeljük a magyar tizedesvesszőt és szeparátort)
df_raw = pd.read_csv('../data/AA_mintafeladat.csv', sep=';', decimal=',', encoding='latin1')
df_raw.head()

,Key,Képzés jogviszony kezdete,Modulkód,KépzésStátusz,Tagozat,Képzési szint,Félév,Pénzügyi státusz,FélévesStátusz,Nem,Születési dátum,Irányítószám,FélévSorszám,Aktív félévek,Féléven felvett kredit,Féléven kumulált felvett kredit,Féléven teljesített kredit,Féléven kumulált teljesített kredit,Átlag,Kumulált átlag
0,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2010.11.01,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,1,7.0,33.0,33.0,33.0,33.0,3.64,3.64
1,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2010.11.02,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,2,7.0,31.0,64.0,31.0,64.0,4.71,4.16
2,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2011.12.01,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,3,7.0,30.0,94.0,30.0,94.0,4.27,4.19
3,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2011.12.02,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,4,7.0,31.0,125.0,31.0,125.0,4.06,4.16
4,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2012/13/1,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,5,7.0,31.0,156.0,31.0,156.0,4.16,4.16

## 3.0 Column Standardization

In [3]:
COLUMN_TRANSLATION = {
    'Key': 'student_id',
    'Képzés jogviszony kezdete': 'enrollment_date',
    'Modulkód': 'major_code',
    'KépzésStátusz': 'status_at_record',
    'Tagozat': 'study_mode',
    'Képzési szint': 'degree_level',
    'Félév': 'semester_id',
    'Pénzügyi státusz': 'funding_type',
    'FélévesStátusz': 'semester_active_status',
    'Nem': 'gender',
    'Születési dátum': 'birth_date',
    'Irányítószám': 'zip_code',
    'FélévSorszám': 'term_number',
    'Aktív félévek': 'total_active_terms',
    'Féléven felvett kredit': 'credits_taken_term',
    'Féléven kumulált felvett kredit': 'credits_taken_cum',
    'Féléven teljesített kredit': 'credits_done_term',
    'Féléven kumulált teljesített kredit': 'credits_done_cum',
    'Átlag': 'gpa_term',
    'Kumulált átlag': 'gpa_cum'
}

df = df_raw.rename(columns=COLUMN_TRANSLATION)
df.head()

,student_id,enrollment_date,major_code,status_at_record,study_mode,degree_level,semester_id,funding_type,semester_active_status,gender,birth_date,zip_code,term_number,total_active_terms,credits_taken_term,credits_taken_cum,credits_done_term,credits_done_cum,gpa_term,gpa_cum
0,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2010.11.01,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,1,7.0,33.0,33.0,33.0,33.0,3.64,3.64
1,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2010.11.02,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,2,7.0,31.0,64.0,31.0,64.0,4.71,4.16
2,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2011.12.01,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,3,7.0,30.0,94.0,30.0,94.0,4.27,4.19
3,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2011.12.02,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,4,7.0,31.0,125.0,31.0,125.0,4.06,4.16
4,1,2010.09.10,ETNEMBSC,Aktív,Nappali,alapképzés (BA/BSc),2012/13/1,Államilag finanszírozott,Aktív,Nõ,dec.91,1126,5,7.0,31.0,156.0,31.0,156.0,4.16,4.16

### 3.1 Categorical Data Audit

In [4]:
# List of categorical columns to investigate
categorical_columns = [
    'status_at_record', 
    'study_mode', 
    'degree_level', 
    'funding_type', 
    'semester_active_status', 
    'gender'
]

print("--- UNIQUE VALUES PER CATEGORICAL COLUMN ---\n")

for col in categorical_columns:
    if col in df.columns:
        unique_values = df[col].dropna().unique().tolist()
        print(f"Column: {col}")
        print(f"Number of unique values: {len(unique_values)}")
        print(f"Values: {unique_values}")
        print("-" * 40)
    else:
        print(f"Error: Column '{col}' not found in the DataFrame!")

--- UNIQUE VALUES PER CATEGORICAL COLUMN ---

Column: status_at_record
Number of unique values: 21
Values: ['Aktív', 'Diplomát szerzett', 'Törölt', 'Passzív', 'Részismeretes(végzett)', 'Záróvizsgát tett', 'Abszolvált', 'Szakváltoztató', 'Sikeres záróvizsga', 'Bejelentés nélkül távozott', 'Aktív vendéghallgató', 'Sikertelen záróvizsga', 'Elhunyt', 'Képzés váltó', 'Még nem meghatározott', 'Saját kérésre törölve', 'Tagozat váltó', 'Felvett', 'Nem beszámító aktív', 'Intézményváltoztató', 'Átsorolva más jelû tantervbe']
----------------------------------------
Column: study_mode
Number of unique values: 2
Values: ['Nappali', 'Levelezõ']
----------------------------------------
Column: degree_level
Number of unique values: 2
Values: ['alapképzés (BA/BSc)', 'mesterképzés (MA/MSc)']
----------------------------------------
Column: funding_type
Number of unique values: 26
Values: ['Államilag finanszírozott', 'Költségtérítéses', 'Államilag támogatott', 'Államilag támogatott (képzési idõn túli)', 'Önköltséges', 'Állami részösztöndíjas', 'Állami ösztöndíjas', 'Költségtérítéses (másoddiplomás)', 'Államilag finanszírozott (képzési idõn túli)', 'Miniszteri ösztöndíjas', 'Költségtérítés mentes (GYES...)', 'Költségtérítéses (képzési idõn túli)', 'A1 kategóriás külföldi ösztöndíjas', 'Részképzés', 'Államilag finanszírozott túllépõ', 'Még nem meghatározott', 'Költségtérítés mentes', 'Normatív támogatással A3 HTM', 'Költségtérítéses (vendéghallgató)', 'B külf. külsõ tám. ösztöndíj', 'Egyéb', 'Államilag támogatott (vendéghallgató)', 'Költségtérítéses (párhuzamos)', 'C kategóriás külföldi ösztöndíjas', 'Önköltséges külföldi', 'A3R Részképzõs HTM normatív támogatással']
----------------------------------------
Column: semester_active_status
Number of unique values: 21
Values: ['Aktív', 'Passzív', 'Aktív vendéghallgató', 'Évhalasztó', 'Akkreditált', 'Felvett', 'Még nem meghatározott', 'Törölt', 'Áthallgató', 'Abszolvált', 'Záróvizsgára vár', 'Szakváltoztató', 'Nem beszámító aktív', 'Részismeretes(végzett)', 'Képzés váltó', 'Elhunyt', 'Bejelentés nélkül távozott', 'Szünetel', 'Átsorolva más jelû tantervbe', 'Passzív vendéghallgató', 'Saját kérésre törölve']
----------------------------------------
Column: gender
Number of unique values: 2
Values: ['Nõ', 'Férfi']
----------------------------------------

## 4.0 Categorical Translation and Mapping

In [5]:
status_at_record_map = {
    "Aktív": "Active",
    "Diplomát szerzett": "Graduated",
    "Törölt": "Deleted",
    "Passzív": "Inactive",
    "Részismeretes(végzett)": "Partial studies completed",
    "Záróvizsgát tett": "Final exam taken",
    "Abszolvált": "Completed coursework (absolved)",
    "Szakváltoztató": "Changed major",
    "Sikeres záróvizsga": "Successful final exam",
    "Bejelentés nélkül távozott": "Left without notice",
    "Aktív vendéghallgató": "Active guest student",
    "Sikertelen záróvizsga": "Failed final exam",
    "Elhunyt": "Deceased",
    "Képzés váltó": "Changed program",
    "Még nem meghatározott": "Not yet defined",
    "Saját kérésre törölve": "Deleted upon own request",
    "Tagozat váltó": "Changed study track",
    "Felvett": "Admitted",
    "Nem beszámító aktív": "Active (non-credit)",
    "Intézményváltoztató": "Changed institution",
    "Átsorolva más jelû tantervbe": "Reclassified to different curriculum"
}

study_mode_map = {
    "Nappali": "Full-time",
    "Levelezõ": "Part-time"
}

degree_level_map = {
    "alapképzés (BA/BSc)": "Bachelor's degree (BA/BSc)",
    "mesterképzés (MA/MSc)": "Master's degree (MA/MSc)"
}

funding_type_map = {
    "Államilag finanszírozott": "State-funded",
    "Költségtérítéses": "Tuition-fee paying",
    "Államilag támogatott": "State-supported",
    "Államilag támogatott (képzési idõn túli)": "State-supported (beyond study period)",
    "Önköltséges": "Self-funded",
    "Állami részösztöndíjas": "Partial state scholarship",
    "Állami ösztöndíjas": "State scholarship",
    "Költségtérítéses (másoddiplomás)": "Tuition-fee paying (second degree)",
    "Államilag finanszírozott (képzési idõn túli)": "State-funded (beyond study period)",
    "Miniszteri ösztöndíjas": "Ministerial scholarship",
    "Költségtérítés mentes (GYES...)": "Tuition-free (childcare leave etc.)",
    "Költségtérítéses (képzési idõn túli)": "Tuition-fee paying (beyond study period)",
    "A1 kategóriás külföldi ösztöndíjas": "A1 category foreign scholarship",
    "Részképzés": "Partial studies",
    "Államilag finanszírozott túllépõ": "State-funded (exceeding study period)",
    "Még nem meghatározott": "Not yet defined",
    "Költségtérítés mentes": "Tuition-free",
    "Normatív támogatással A3 HTM": "A3 HTM with normative support",
    "Költségtérítéses (vendéghallgató)": "Tuition-fee paying (guest student)",
    "B külf. külsõ tám. ösztöndíj": "B foreign external support scholarship",
    "Egyéb": "Other",
    "Államilag támogatott (vendéghallgató)": "State-supported (guest student)",
    "Költségtérítéses (párhuzamos)": "Tuition-fee paying (parallel program)",
    "C kategóriás külföldi ösztöndíjas": "C category foreign scholarship",
    "Önköltséges külföldi": "Self-funded foreign student",
    "A3R Részképzõs HTM normatív támogatással": "A3R partial training HTM with normative support"
}

semester_active_status_map = {
    "Aktív": "Active",
    "Passzív": "Inactive",
    "Aktív vendéghallgató": "Active guest student",
    "Évhalasztó": "Deferred year",
    "Akkreditált": "Accredited",
    "Felvett": "Admitted",
    "Még nem meghatározott": "Not yet defined",
    "Törölt": "Deleted",
    "Áthallgató": "Cross-registered student",
    "Abszolvált": "Completed coursework (absolved)",
    "Záróvizsgára vár": "Awaiting final exam",
    "Szakváltoztató": "Changed major",
    "Nem beszámító aktív": "Active (non-credit)",
    "Részismeretes(végzett)": "Partial studies completed",
    "Képzés váltó": "Changed program",
    "Elhunyt": "Deceased",
    "Bejelentés nélkül távozott": "Left without notice",
    "Szünetel": "On leave",
    "Átsorolva más jelû tantervbe": "Reclassified to different curriculum",
    "Passzív vendéghallgató": "Inactive guest student",
    "Saját kérésre törölve": "Deleted upon own request"
}

gender_map = {
    "Nõ": "Female",
    "Férfi": "Male"
}

# Apply replacements
df["status_at_record"] = df["status_at_record"].replace(status_at_record_map)
df["study_mode"] = df["study_mode"].replace(study_mode_map)
df["degree_level"] = df["degree_level"].replace(degree_level_map)
df["funding_type"] = df["funding_type"].replace(funding_type_map)
df["semester_active_status"] = df["semester_active_status"].replace(semester_active_status_map)
df["gender"] = df["gender"].replace(gender_map)

# Final check for missing values in processed columns
print(df[categorical_columns].isna().sum())

status_at_record          0
study_mode                0
degree_level              0
funding_type              0
semester_active_status    0
gender                    0
dtype: int64

## 5.0 Temporal Feature Engineering

In [6]:
temp_year = df['birth_date'].str.slice(-2).astype(int)
df['birth_date'] = temp_year.apply(lambda x: 1900 + x if x > 25 else 2000 + x)
df.rename(columns={'birth_date': 'birth_year'}, inplace=True)

df.head()

,student_id,enrollment_date,major_code,status_at_record,study_mode,degree_level,semester_id,funding_type,semester_active_status,gender,birth_year,zip_code,term_number,total_active_terms,credits_taken_term,credits_taken_cum,credits_done_term,credits_done_cum,gpa_term,gpa_cum
0,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2010.11.01,State-funded,Active,Female,1991,1126,1,7.0,33.0,33.0,33.0,33.0,3.64,3.64
1,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2010.11.02,State-funded,Active,Female,1991,1126,2,7.0,31.0,64.0,31.0,64.0,4.71,4.16
2,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2011.12.01,State-funded,Active,Female,1991,1126,3,7.0,30.0,94.0,30.0,94.0,4.27,4.19
3,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2011.12.02,State-funded,Active,Female,1991,1126,4,7.0,31.0,125.0,31.0,125.0,4.06,4.16
4,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2012/13/1,State-funded,Active,Female,1991,1126,5,7.0,31.0,156.0,31.0,156.0,4.16,4.16

## 5.1 Age at Enrollment

In [7]:
df['enrollment_year'] = pd.to_datetime(df['enrollment_date'], errors='coerce').dt.year
df['age_at_enrollment'] = df['enrollment_year'] - df['birth_year']
df['age_at_enrollment'] = df['age_at_enrollment'].clip(lower=18, upper=70)

print("Age at enrollment distribution:")
print(df['age_at_enrollment'].describe())

Age at enrollment distribution:
count    63262.000000
mean        21.433673
std          3.969600
min         18.000000
25%         19.000000
50%         20.000000
75%         23.000000
max         60.000000
Name: age_at_enrollment, dtype: float64

## 6.0 Find Missing Values

In [8]:
# Hiányzó értékek abszolút és százalékos aránya
missing_data = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Percentage (%)': (df.isnull().sum() / len(df)) * 100
}).sort_values(by='Percentage (%)', ascending=False)

print("--- MISSING DATA REPORT ---")
print(missing_data[missing_data['Missing Values'] > 0])

--- MISSING DATA REPORT ---
                    Missing Values  Percentage (%)
gpa_cum                      10430       16.486991
credits_done_cum             10430       16.486991
credits_taken_cum            10430       16.486991
credits_done_term            10426       16.480668
gpa_term                     10426       16.480668
credits_taken_term            2853        4.509816
zip_code                        29        0.045841
total_active_terms              10        0.015807

## 6.1 Handle Missing Values

In [9]:
cols_to_fix = [
    'gpa_cum', 'credits_taken_cum', 'credits_done_cum', 
    'credits_done_term', 'gpa_term', 'credits_taken_term'
]
df[cols_to_fix] = df[cols_to_fix].fillna(0.0)
df['total_active_terms'] = df['total_active_terms'].fillna(1.0)

df.dropna(subset=['zip_code'], inplace=True)

print(f"Remaining missing values: {df.isnull().sum().sum()}")

Remaining missing values: 0

## 7.0 Geographic Mapping: ZIP to County

In [10]:
county_mapping = {
    '20': 'Pest', '21': 'Pest', '22': 'Pest', '23': 'Pest', '27': 'Pest',
    '24': 'Fejér', '80': 'Fejér', '81': 'Fejér',
    '25': 'Komárom-Esztergom', '28': 'Komárom-Esztergom', '29': 'Komárom-Esztergom',
    '26': 'Nógrád', '31': 'Nógrád',
    '30': 'Heves', '32': 'Heves', '33': 'Heves',
    '34': 'Borsod-Abaúj-Zemplén', '35': 'Borsod-Abaúj-Zemplén', '36': 'Borsod-Abaúj-Zemplén', 
    '37': 'Borsod-Abaúj-Zemplén', '38': 'Borsod-Abaúj-Zemplén', '39': 'Borsod-Abaúj-Zemplén',
    '40': 'Hajdú-Bihar', '41': 'Hajdú-Bihar', '42': 'Hajdú-Bihar',
    '43': 'Szabolcs-Szatmár-Bereg', '44': 'Szabolcs-Szatmár-Bereg', '45': 'Szabolcs-Szatmár-Bereg', 
    '46': 'Szabolcs-Szatmár-Bereg', '47': 'Szabolcs-Szatmár-Bereg', '48': 'Szabolcs-Szatmár-Bereg', '49': 'Szabolcs-Szatmár-Bereg',
    '50': 'Jász-Nagykun-Szolnok', '51': 'Jász-Nagykun-Szolnok', '52': 'Jász-Nagykun-Szolnok', '53': 'Jász-Nagykun-Szolnok', '54': 'Jász-Nagykun-Szolnok',
    '55': 'Békés', '56': 'Békés', '57': 'Békés', '58': 'Békés', '59': 'Békés',
    '60': 'Bács-Kiskun', '61': 'Bács-Kiskun', '62': 'Bács-Kiskun', '63': 'Bács-Kiskun', '64': 'Bács-Kiskun', '65': 'Bács-Kiskun', '69': 'Bács-Kiskun',
    '66': 'Csongrád-Csanád', '67': 'Csongrád-Csanád', '68': 'Csongrád-Csanád',
    '70': 'Tolna', '71': 'Tolna', '72': 'Tolna',
    '73': 'Baranya', '76': 'Baranya', '77': 'Baranya', '78': 'Baranya', '79': 'Baranya',
    '74': 'Somogy', '75': 'Somogy', '86': 'Somogy', '87': 'Somogy',
    '82': 'Veszprém', '84': 'Veszprém', '85': 'Veszprém',
    '83': 'Zala', '88': 'Zala', '89': 'Zala',
    '90': 'Győr-Moson-Sopron', '91': 'Győr-Moson-Sopron', '92': 'Győr-Moson-Sopron', '93': 'Győr-Moson-Sopron', '94': 'Győr-Moson-Sopron',
    '95': 'Vas', '96': 'Vas', '97': 'Vas', '98': 'Vas', '99': 'Vas'
}

zip_prefixes = df['zip_code'].astype(str).str[:2]

df['county'] = zip_prefixes.map(lambda x: 'Budapest' if x.startswith('1') else county_mapping.get(x, 'Unknown/Foreign'))

print("County assignment finished. Sample results:")
print(df[['zip_code', 'county']].head())

County assignment finished. Sample results:
  zip_code    county
0     1126  Budapest
1     1126  Budapest
2     1126  Budapest
3     1126  Budapest
4     1126  Budapest

## 8.0 Funding Type Simplification

In [11]:
state_funded_keywords = [
    'State-funded', 'State-supported', 'State-scholarship', 
    'Ministerial scholarship', 'Partial state scholarship',
    'A1 category foreign scholarship', 'C category foreign scholarship',
    'B foreign external support scholarship'
]

df['funding_category'] = df['funding_type'].apply(
    lambda x: 'State-funded' if any(key in str(x) for key in state_funded_keywords) else 'Self-funded'
)

print(df['funding_category'].value_counts())

funding_category
State-funded    38031
Self-funded     25202
Name: count, dtype: int64

## 8.1 Churn Target Definition

In [12]:
churn_statuses = [
    'Deleted', 
    'Left without notice', 
    'Failed final exam', 
    'Deleted upon own request', 
    'Inactive'
]

df['is_churned'] = df['status_at_record'].isin(churn_statuses).astype(int)

print("Churn distribution (Target Variable):")
print(df['is_churned'].value_counts(normalize=True) * 100)

Churn distribution (Target Variable):
is_churned
0    79.126406
1    20.873594
Name: proportion, dtype: float64

## 9.0 Major Field Extraction

In [13]:
major_inventory = df['major_code'].value_counts().reset_index()
major_inventory.columns = ['unique_major_code', 'record_count']
major_inventory = major_inventory.sort_values(by='unique_major_code')
print(major_inventory)

all_codes = major_inventory['unique_major_code'].tolist()

   unique_major_code  record_count
25          1MLELELM           210
20          1MNELELM           620
14           2BLGINF          1354
8            2BLGMEN          3091
6           2BNGINFB          3539
0            2BNGMEN          7160
9            2BNNKGA          2725
1            2BNPSZV          6363
18           2MNGINF           813
16             2MNPU          1295
17            2MNSZV          1137
11           2MNVESZ          2589
10           3BLKEMN          2659
4            3BNKEMN          4335
22           3MLKERT           408
23           3MNKERT           298
7            4BNAKGT          3514
21          4MNKOZEL           553
5            6BNTRKM          4019
19            6MNTAJ           659
12           7BNKOMM          2258
2            7BNNEMZ          5368
24           7BNTARS           285
13           7MNNEMZ          1758
15          ETLEMBSC          1302
3           ETNEMBSC          4921

## 9.1 University and Major Name Enrichment

In [14]:
academic_mapping = {
    '1MLELELM': ('MATE', 'Food Engineering (MSc)'),
    '1MNELELM': ('MATE', 'Food Engineering (MSc)'),
    '2BLGINF':  ('Corvinus', 'Business Informatics (BSc)'),
    '2BLGMEN':  ('Corvinus', 'Business and Management (BSc)'),
    '2BNGINFB': ('Corvinus', 'Business Informatics (BSc)'),
    '2BNGMEN':  ('Corvinus', 'Business and Management (BSc)'),
    '2BNNKGA':  ('Corvinus', 'International Business (BSc)'),
    '2BNPSZV':  ('Corvinus', 'Finance and Accounting (BSc)'),
    '2MNGINF':  ('Corvinus', 'Business Informatics (MSc)'),
    '2MNPU':    ('Corvinus', 'Finance (MSc)'),
    '2MNSZV':   ('Corvinus', 'Accounting (MSc)'),
    '2MNVESZ':  ('Corvinus', 'Management and Organization (MSc)'),
    '3BLKEMN':  ('Corvinus', 'Commerce and Marketing (BSc)'),
    '3BNKEMN':  ('Corvinus', 'Commerce and Marketing (BSc)'),
    '3MLKERT':  ('Corvinus', 'Marketing (MSc)'),
    '3MNKERT':  ('Corvinus', 'Marketing (MSc)'),
    '4BNAKGT':  ('Corvinus', 'Applied Economics (BSc)'),
    '4MNKOZEL': ('Corvinus', 'Economic Analyst (MSc)'),
    '6BNTRKM':  ('Corvinus', 'Tourism and Catering (BSc)'),
    '6MNTAJ':   ('MATE', 'Landscape Architecture (MSc)'),
    '7BNKOMM':  ('Corvinus', 'Communication and Media Science (BSc)'),
    '7BNNEMZ':  ('Corvinus', 'International Studies (BSc)'),
    '7BNTARS':  ('Corvinus', 'Sociology (BSc)'),
    '7MNNEMZ':  ('Corvinus', 'International Studies (MSc)'),
    'ETLEMBSC': ('MATE', 'Food Engineering (BSc)'),
    'ETNEMBSC': ('MATE', 'Food Engineering (BSc)')
}


df['university'] = df['major_code'].apply(lambda x: academic_mapping.get(x, ('Unknown', 'Unknown'))[0])
df['major_name_en'] = df['major_code'].apply(lambda x: academic_mapping.get(x, ('Unknown', 'Unknown'))[1])


df.head()

,student_id,enrollment_date,major_code,status_at_record,study_mode,degree_level,semester_id,funding_type,semester_active_status,gender,...,credits_done_cum,gpa_term,gpa_cum,enrollment_year,age_at_enrollment,county,funding_category,is_churned,university,major_name_en
0,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2010.11.01,State-funded,Active,Female,...,33.0,3.64,3.64,2010,19,Budapest,State-funded,0,MATE,Food Engineering (BSc)
1,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2010.11.02,State-funded,Active,Female,...,64.0,4.71,4.16,2010,19,Budapest,State-funded,0,MATE,Food Engineering (BSc)
2,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2011.12.01,State-funded,Active,Female,...,94.0,4.27,4.19,2010,19,Budapest,State-funded,0,MATE,Food Engineering (BSc)
3,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2011.12.02,State-funded,Active,Female,...,125.0,4.06,4.16,2010,19,Budapest,State-funded,0,MATE,Food Engineering (BSc)
4,1,2010.09.10,ETNEMBSC,Active,Full-time,Bachelor's degree (BA/BSc),2012/13/1,State-funded,Active,Female,...,156.0,4.16,4.16,2010,19,Budapest,State-funded,0,MATE,Food Engineering (BSc)

## 9.2 Academic Efficiency

In [15]:
df['academic_efficiency'] = np.where(
    df['credits_taken_cum'] > 0, 
    df['credits_done_cum'] / df['credits_taken_cum'], 
    0.0
)

df['academic_efficiency'] = df['academic_efficiency'].round(3)

print("Average academic efficiency by university:")
print(df.groupby('university')['academic_efficiency'].mean())

Average academic efficiency by university:
university
Corvinus    0.694620
MATE        0.609473
Name: academic_efficiency, dtype: float64

## 9.3 Major Field Categorization

In [16]:
def get_broad_field(major_name):
    name = str(major_name)
    if any(x in name for x in ['Business', 'Finance', 'Accounting', 'Management', 'Economics', 'Marketing', 'Commerce']):
        return 'Economics & Business'
    elif 'Informatics' in name:
        return 'IT'
    elif any(x in name for x in ['Food', 'Landscape']):
        return 'Agriculture & Engineering'
    elif any(x in name for x in ['International', 'Communication', 'Sociology']):
        return 'Social Sciences'
    elif 'Tourism' in name:
        return 'Tourism'
    return 'Other'


df['major_field_broad'] = df['major_name_en'].apply(get_broad_field)

print("Records per Broad Field:")
print(df['major_field_broad'].value_counts())

Records per Broad Field:
major_field_broad
Economics & Business         41280
Social Sciences               9669
Agriculture & Engineering     7712
Tourism                       4019
Other                          553
Name: count, dtype: int64

## 9.4 Column Reordering (Logical Schema)

In [17]:
ordered_columns = [
    # 1. Identifiers & Dates
    'student_id', 'semester_id', 'term_number', 'enrollment_date', 'enrollment_year',
    
    # 2. Demographics
    'gender', 'birth_year', 'age_at_enrollment',
    
    # 3. Geography
    'zip_code', 'county',
    
    # 4. Academic Background
    'university', 'major_code', 'major_name_en', 'major_field_broad', 
    'degree_level', 'study_mode',
    
    # 5. Financials & Status
    'funding_type', 'funding_category', 'semester_active_status', 'status_at_record',
    
    # 6. Performance Metrics
    'total_active_terms', 
    'credits_taken_term', 'credits_taken_cum', 
    'credits_done_term', 'credits_done_cum', 
    'gpa_term', 'gpa_cum', 'academic_efficiency',
    
    # 7. Target Variable
    'is_churned'
]

current_cols = set(df.columns)
ordered_set = set(ordered_columns)

missing_from_order = current_cols - ordered_set
if missing_from_order:
    print(f"Warning: These columns were not in the list: {missing_from_order}")
    ordered_columns += list(missing_from_order)

df = df[ordered_columns]

print("Columns successfully reordered. New schema preview:")
print(df.iloc[:, :29].info())

Columns successfully reordered. New schema preview:
<class 'pandas.DataFrame'>
Index: 63233 entries, 0 to 63261
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              63233 non-null  int64
 1   semester_id             63233 non-null  str
 2   term_number             63233 non-null  int64
 3   enrollment_date         63233 non-null  str
 4   enrollment_year         63233 non-null  int32
 5   gender                  63233 non-null  str
 6   birth_year              63233 non-null  int64
 7   age_at_enrollment       63233 non-null  int64
 8   zip_code                63233 non-null  str
 9   county                  63233 non-null  str
 10  university              63233 non-null  str
 11  major_code              63233 non-null  str
 12  major_name_en           63233 non-null  str
 13  major_field_broad       63233 non-null  str
 14  degree_level            63233 non-null  str
 15  study_mode              63233 non-null  str
 16  funding_type            63233 non-null  str
 17  funding_category        63233 non-null  str
 18  semester_active_status  63233 non-null  str
 19  status_at_record        63233 non-null  str
 20  total_active_terms      63233 non-null  float64
 21  credits_taken_term      63233 non-null  float64
 22  credits_taken_cum       63233 non-null  float64
 23  credits_done_term       63233 non-null  float64
 24  credits_done_cum        63233 non-null  float64
 25  gpa_term                63233 non-null  float64
 26  gpa_cum                 63233 non-null  float64
 27  academic_efficiency     63233 non-null  float64
 28  is_churned              63233 non-null  int64
dtypes: float64(8), int32(1), int64(5), str(15)
memory usage: 14.2 MB
None

## 10.0 Final Data Integrity Check & Export

In [18]:
df.to_csv('../data/student_data_cleaned.csv', index=False, encoding='utf-8')
print("\nSUCCESS: Preprocessing complete.")

SUCCESS: Preprocessing complete.